# Generated by Django 5.2.3 on 2025-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processind', 'درحال پردازش'), ('Shipped', 'ارسال شده به پست'), ('pending', 'تحویل داده شده')], default='Pending', max_length=50),
        ),
    ]
